# specify version of docker compose 
version: '3'
# initialize section for building the containers
services:
# first service (container) name, used to connect
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./nf_tumor_backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./nf_tumor_backend:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres