# specify version of docker compose 
version: '3'
# initialize section for building the containers
services:
# first service (container) name, used to connect
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./nf_tumor_backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./nf_tumor_backend:/myapp
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./nf_tumor_app
    volumes:
      - /usr/src/app/node_modules
      - ./nf_tumor_app:/usr/src/app
  datascience:
    build:
      dockerfile: Dockerfile.dev
      context: ./NF_Kids_App_PythonAPI
    volumes:
      - ./NF_Kids_App_PythonAPI:/usr/src/app